### ISSUE TITLE
unity exporting issues

### ISSUE THREAD

**Issue by vinodkrishna221** [makehumancommunity/mpfb2#112]
when i export my models to unity eyes texture is not visible.pls can you tell me how to fix it, because i don't have much time i want to compleate my game as fast as possible.

also other textures of hair and skin are not same as rendered model in blender and unity pls give me some advice to get rid of these problems

**Comment by joepal1976** [comment]
First, you need to understand that there are fundamental differences between blender materials and unity materials, especially in the cases where more advanced blender functionality is used. Explaining these differences and how to overcome them is beyond what I can explain here, but I'd encourage you to watch, for example, https://www.youtube.com/watch?v=yloupOUjMOA

This said, the easiest way to translate from blender to unity is to only use dumb materials consisting of a diffuse texture and possibly a normal map.

You need to:

- set skin model to v0 makeskin
- disable material instances
- disable procedural eyes:

Your library settings should look like this:

<img width="145" alt="image" src="https://github.com/makehumancommunity/mpfb2/assets/10105480/fbc0cba5-4936-4e44-a0cd-25e0c5e88925">

Note that these apply the next time you add an asset, it will not change already loaded assets.

Then you probably best off using "low-poly eyes" rather than "high-poly" to avoid transparency problems:

<img width="144" alt="image" src="https://github.com/makehumancommunity/mpfb2/assets/10105480/811a93a7-dc0b-49db-9505-518d35f66213">

With these settings, you can then export a character via FBX. You are best off selecting the hierarchy with skeleton, bodyparts, body, hair and clothes and then only export selected objects.

In unity, you need to set a material rendering mode that takes texture alpha into account. 

Without doing so, this is what you get:

<img width="901" alt="image" src="https://github.com/makehumancommunity/mpfb2/assets/10105480/87223edf-2a0a-44d8-b645-0c97223481b7">

But if you correctly set rendering mode, this is what you get:

<img width="902" alt="image" src="https://github.com/makehumancommunity/mpfb2/assets/10105480/944c03d7-f7cd-4bb3-ba35-0a4643e7ea03">

**Comment by joepal1976** [comment]
Closing this in favor of #138
