### ISSUE TITLE
Provide roadmap and milestones

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#132]
This is a bit meta - it isn't code per se. But it'd probably be useful to:

- Provide a roadmap on the web site
- Declare milestones here in the git repo
- Tag issues with which milestone they belong to (if relevant)

This way, users could get at least a very rough idea of what is planned for the next release and what is planned for a more distant future.

**Comment by joepal1976** [comment]
Preliminary milestones: https://github.com/makehumancommunity/mpfb2/milestones?direction=asc&sort=due_date&state=open

**Comment by joepal1976** [comment]
I'd love some feedback on this: Is there anything else which should be added to the stuff mentioned above?

**Comment by joepal1976** [comment]
Thinking this is good enough for now.

**Comment by ashledombos** [comment]
I understand the issue is already closed, but I needed some time to reflect on it. Here are some suggestions for the roadmap:

- Consider enhancing the default armature to incorporate Blender 4's new joint colors and bone collections;
- Introduce a variety of preset poses and expressions, while also allowing the community to contribute custom poses and expressions;
- Create a mechanism for the community to offer preset human models;
- Go even further by allowing artists to supply character packs, such as a preset human model with a limited set of shape keys, hairstyles, and garments, without requiring a full MPFB plugin download. For example, a system similar to what MustardUI offers, allowing for a character resembling Adam from Masters of the Universe, complete with toggles and sliders to transform him into He-Man;
- Auto-rig-pro is a fairly popular paid rigging solution; it might be worthwhile to reach out to the creator to discuss the possibility of easily applying an ARP armature to a MakeHuman model.

**Comment by joepal1976** [comment]
All very valid suggestions. 

This particular issue was for having a roadmap and milestones at all, ie to create the roadmap page and the milestone tags. The roadmap is by no means closed just because this issue is closed. 

So from my point of view: Feel free to create feature request isses for the above, and we can then tag them with milestone tags and add them to the roadmap page.

**Comment by ashledombos** [comment]
This is done, plus another one :)
