### ISSUE TITLE
Set up rigging / fit to body is enabled BUT...

### ISSUE THREAD

**Issue by Vidyut** [makehumancommunity/mpfb2#134]
I already had my characters generated for a while, so I can't say when this started, but today when I tried to make a new character from a preset and I try to add eyes to it I get "set up rigging is enabled but no rig found" even though MPFB2 has generated the metarig moments ago or if I select the rig so MPFB2 can see it, " fit to body is selected but no mesh found or some such.

It is possible that I may be doing something wrong, but I don't remember struggling with this before. Seems to be a fairly glaring issue and nobody else seems to be reporting it, so not sure if it is just me.

**Comment by joepal1976** [comment]
If this is a character that was generated a while back and which you loaded from a blend file, it is possible the character is missing a property. There was a bug in which the property was not set on generated rigs. This isn't a disaster and can be fixed afterwards.

In blender, select the rig and find the object properties -> custom properties panel:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/bb1c36e8-748c-485d-a079-dbf1d943beef)

If the rig does not have the "MPFB_GEN_object_type" property, then add it and set it to "Skeleton".

Having done so, it should then be possible to add clothes again.

However, I would have assumed that the property should be added when generating. Note that you need to use MPFB's generate functionality in order for this to work though, you can't manually generate the rig and expect it to retain MPFB properties. This is the panel which you need to use in order to get the MPFB properties set:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/8e177689-c1be-4f4b-bb07-47b8deed5e6f)

**Comment by Vidyut** [comment]
Will try it out the next time I start blender and confirm here.

**Comment by Vidyut** [comment]
Unhandled exception: Pose bone has no object rigify type. During creation of the human. Also the process ends in pose mode. Pretty sure it used to remain/end in object mode before.

**Comment by joepal1976** [comment]
Ok, so the rigify stuff this issue was about aren't relevant anymore? I'd suggest closing this issue then and taking the stuff that relates to MakeSkin in #129

**Comment by Vidyut** [comment]
The rigify complication was of my own making. I'd forgotten I disabled rigify to see if it would save without it and forgot.
