### ISSUE TITLE
MPFB2 needs a PBR material which translates to external game engines (since the MakeSkin model does not)

### ISSUE THREAD

**Issue by Miracle8248** [makehumancommunity/mpfb2#138]
Actually I want to export my model rigged and textured so that I can use that in any software but when i export from blender and upload it into blender I see there are no textures so how can I get textures in my fbx files even i export with textures

**Comment by joepal1976** [comment]
As said, how Blender handles FBX exports is something MPFB has somewhat limited control over. The same goes for how external applications then handles the FBX exports. 

This said, it is obvously problematic that Blender cannot export a rather simple material and then read it back. I have no good solution for this right now. Maybe there is something which could be done with how materials are defined. I will have to research this.

In the meantime, there is an instruction video for Unity where a procedure for getting around the issue is demonstrated (explicitly listing the materials in unity after import). Maybe that can be of some help: https://youtu.be/YypDcUpON8A?si=YCxHg9sc3KN1WoQR

I'll convert the current issue into a but report for investigating what can be done (if anything) about FBX exports.

**Comment by Miracle8248** [comment]
Ok thanks i hope problem will solved

**Comment by Miracle8248** [comment]
And one more problem there are no textures I'm unreal engine 5 too

**Comment by joepal1976** [comment]
Further research: Blender will manage to persist a diffuse texture to FBX only if it is directly connected to the color socket on the principled node. Otherwise it will be bundled but ignored on import.

Unfortunately, wiring the connection that way will break the PBR setup of MakeSkin. But maybe it would be possible to have a drastically simplified material setup specifically for external applications? Research continues...

**Comment by joepal1976** [comment]
There is now basic support for a new material type "GameEngine". Before creating or adding any character or assets, set material types in the library settings panel:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/dda6137d-e88a-4ff5-8d36-dd371c4e629d)

Note that this is only available in the blender4 branch and blender4 nightly builds.

Note to self, still to do:

- Allow overriding to game engine for skin, eyes and clothes when loading from preset
- Allow usage of game engine when importing from makehuman
- Allow usage of game engine when loading from an explicit mhclo file
- Check serialization of game engine material when saving a preset
- Handle game engine material in alternate material dropdown

**Comment by joepal1976** [comment]
Now the game engine material works with eyes, bodyparts, clothes and skin. It can be serialized and deserialized. When exporting a character with game engine materials to FBX and then importing it back into blender, the character looks reasonably the same. 

Remains to test exports with actual game engines such as unity.

**Comment by joepal1976** [comment]
Assumed to be working as intended. Open new issues if something is wrong with it.

**Comment by Miracle8248** [comment]
Ok thanks

**Comment by Miracle8248** [comment]
> Assumed to be working as intended. Open new issues if something is wrong with it.

I am sorry if I waste your time

**Comment by Miracle8248** [comment]
Ok thanks I will report any issues if I find in future too 👍
