### ISSUE TITLE
MPFB materials look strange or broken when moved between blender 4 and blender 3.6

### ISSUE THREAD

**Issue by dhyowi** [makehumancommunity/mpfb2#162]
![Screenshot 2023-12-08 124743](https://github.com/makehumancommunity/mpfb2/assets/21953048/142e5a1b-213a-4915-b6c5-6ebb045f47ee)
High poly eyes turn white when I open a saved file.

**Screenshots / logs**

If there was a crash or if you think the logs would be useful, attach a log file. You can find a "export log" button on the "developer" panel in MPFB.

**Platform and versions**
 - OS: Windows 11
 - 3.6 and 4.0
 - Version of MPFB MPFB2 11/19/23 build and previous builds up to 10/16/23

**Comment by joepal1976** [comment]
Are you using a texture based material or the procedural material for the eyes?

**Comment by joepal1976** [comment]
Ok, I'm going to need some more information to debug this. 

I've written a new guide on what kind of information is needed: http://static.makehumancommunity.org/mpfb/faq/help_debugging.html

Can you take a look at that and provide screenshots of the system panel, the material panel and the shader nodes view?

**Comment by dhyowi** [comment]
![Screenshot 2023-12-10am](https://github.com/makehumancommunity/mpfb2/assets/21953048/31c11fd7-9d7a-4df4-b53d-2aa8c759eba3)

My problem with debugging is that I was always in Eevee during editing and in Material Preview as well. I only realized the problem when I was going to render in Cycles and noticed that the eyes where all white. Hence, I can't trace when the issue arose. This only appears in Cycles render. Thanks for the time! Appreciate it a lot.

**Comment by dhyowi** [comment]
> Ok, I'm going to need some more information to debug this.
> 
> I've written a new guide on what kind of information is needed: http://static.makehumancommunity.org/mpfb/faq/help_debugging.html
> 
> Can you take a look at that and provide screenshots of the system panel, the material panel and the shader nodes view?

/
/

I was able to recreate the issue by creating human with high poly eyes in Blender 4.0 with latest ver. of  MPFB2 and appending it in Blender 3.6 with MPFB2 ver. 2023/10/16.
![Screenshot 2023-12-10am](https://github.com/makehumancommunity/mpfb2/assets/21953048/54dda0ad-63e0-432c-8b23-58aa6a088f0a)

**Comment by joepal1976** [comment]
That is actually not surprising at all. Blender 4 shader nodes are not compatible with blender 3.6. While a lot still looks the same, there are key parts which do not translate.

It's hard to say exactly which incompatibility that triggers this exact phenomenon, but I'm actually more surprised that you managed to append the node model at all.

**Comment by dhyowi** [comment]
> That is actually not surprising at all. Blender 4 shader nodes are not compatible with blender 3.6. While a lot still looks the same, there are key parts which do not translate.
> 
> It's hard to say exactly which incompatibility that triggers this exact phenomenon, but I'm actually more surprised that you managed to append the node model at all.

Thanks so much for the info. Sometimes it closes unexpectedly but stable most of the time. So far those are the only issues I've encountered. If I may ask, are there changes made to the human models  per.build like contour and shapes of various body parts, especially the face? Is it ok to use and edit models from different builds of MPFB2. Also, I noticed that rigify loses.the option to choose visibility and selection of particular bone groups when changing from Blender 3.6 - 4 and vice versa.

Thanks so much for the support. I'm a relatively new Blender user and so far find that the community is very friendly and encouraging.

**Comment by joepal1976** [comment]
That's only for the best: The aim is that MPFB should be easy and understandable for everyone, not just blender veterans. So testing and feedback is very welcome.

To answer the questions, there are two different scenarios:

- You model and dress a character in one blender version, save a preset and open the preset in another version.
- You model and dress a character in one blender version and either copy/paste, append or open the blend file in another version.

In the first scenario, everything should look exactly the same. You might need to adjust subsurface settings in a material if you changed that, but otherwise everything should translate.

In the second scenario, things are quite a lot more shaky. I would not recommend trying to work with blender 4 and blender 3 in parallel and try to move blend data between them. You will run into problems when doing that, especially when it comes to material and rigify. 

As a context, the two things that changed the most in incompatible ways between blender 4 and blender 3 are those two things: shader nodes and rigify. 

If at all possible, I'd recommend moving everything to blender 4. While we're not there yet, MPFB2 is likely to become blender 4 only in a not too distant future.

**Comment by joepal1976** [comment]
As a slight modification: things *should* look the same when working with presets in different versions of blender.

If they do not, then that's a bug that I'll want to hear about.
