### ISSUE TITLE
Write a changelog for what is to become the next release

### ISSUE THREAD

**Issue by Vidyut** [makehumancommunity/mpfb2#184]
I'm probably being dense. Had to take a break from blendering due to personal reasons and now that I'm back, I'm refamiliarising myself with the addon. I see that there are bug requests and enhancement requests, etc, some resolved, and so on, but I'm not sure where to get a list of fixes or enhancements already implemented. As I understand, we aren't supposed to download the addon from here, but from the makehuman repository, but that just contains the files, not a changelog.

If somebody needs a quick look of what new features are implemented, where to look?

**Comment by joepal1976** [comment]
That's me, not you. I'm behind on updating the site with such content. 

The theory is that a new release notes page should be started for beta 1 and end up somewhere in this hierarchy: https://static.makehumancommunity.org/mpfb/releases.html

I'm hoping to start this the next few days.

**Comment by joepal1976** [comment]
I've started the changelog at https://static.makehumancommunity.org/mpfb/releases/release_next.html

I realize this might be in a language which is too general to get detailed understanding of what has changed during the last few months. But from the viewpoint of the things you worked with, I'd say that the situation is essentially the same. There are, for example, no conflicts between master and the "blender4_measure" branch.

The most important change is that the blender4 code is now merged to master.

**Comment by Vidyut** [comment]
Sooper. If there's a team working on documentation, I could help them. I don't know enough to give instructions, but I'm a writer. I can write :) Surely that can be useful...

**Comment by joepal1976** [comment]
"Team" is such a strong word. :-) It's basically me adding docs regarding MPFB and PunkDuck trying to update the docs regarding MakeHuman and MakeClothes.

Any help with docs is welcome. What's sorely needed is beginner-friendly basic documentation with easy to read text explaining the UI and how to perform basic operations. Like "how to model a human", "how to pose a human", "the different available materials" and stuff like that. 

All docs are written as markdown files (with some added stuff) here: https://github.com/makehumancommunity/makehuman-static-website/tree/master/content/MPFB/Docs, for example the getting started guide at https://raw.githubusercontent.com/makehumancommunity/makehuman-static-website/master/content/MPFB/Docs/getting_started.md

The "added stuff" are the "relref" instructions for linking to other places in the docs and the header with the metadata, otherwise everything is plain markdown.

So if you want to contribute docs, just make a PR against the makehuman-static-website repo. 

A working markdown file is enough, I can add relrefs and headers afterwards. Or if you want to test to launch the entire site locally to see how it ends up looking, these are the command line instructions for "hugo" (which is what we use to convert the markdown to html) :

- Make sure you have python 3.x available
- download and install "hugo extended", from https://github.com/gohugoio/hugo/releases (expand the "assets" part of a release to see a deb for example... it's important that it is "extended" and not just "hugo")
- `git clone --recurse-submodules git@github.com:makehumancommunity/makehuman-static-website.git`
- `cd makehuman-static website`
- `python bin/launch.py`

**Comment by joepal1976** [comment]
Closing this as fixed, as there are now preliminary release notes available.
