### ISSUE TITLE
Seamless custom shaders.... How?

### ISSUE THREAD

**Issue by emberlightstudios** [makehumancommunity/mpfb2#187]
This is not an issue with your software.  

As you know we are porting this into a plugin for the godot game engine.  I'm just wondering how you managed to generate procedural materials which do not show seams.  Every time I try to make one in godot the seams are very obvious, but in mpfb there are no seams at all.

I tried looking through your shaders a bit and I noticed you use the texture coordinate node with the "object" output.  I don't know if this is related or what it does really.  How did you manage to get the noise textures to line up perfectly at the seams as if it were a texture painted directly on the mesh?  I'm just completely baffled.

**Comment by matt-seaton** [comment]
I was making an attempt to do something similar.  I started with a solid black texture then filled the character with white, took the b&w texture to gimp and put a gaussian blur on it to get some gray around the seams to use for blending.  It was tricky but it kind of worked for what i was trying to do.  I think these textures will be very useful. Thanks.

**Comment by joepal1976** [comment]
Ah, that seam. 

That's because there is no seam there, from the point of view of the texture. The image textures and the zone masks use UV coordinates, but the procedural aspects mostly use "generated" or "object" coordinates. 

This is particularly visible in the breasts area. If you look at a character with D-cup breasts, you will see that an image texture is stretched to fill the space. But the procedural pore bumps remain the same size rather than stretching.

If you navigate down through the group nodes in the shader tree, you will eventually find a few nodes of the "texture coordinates" type where you'll see that different output sockets are used depending on what aspect of the shader the coordinates are for.

**Comment by Vidyut** [comment]
Hi @matt-seaton I'd found this video helpful https://www.youtube.com/watch?v=tydrEVlHRb4

(assuming what I was struggling with and what you want to know are similar) Then @joepal1976's map suggestion should work?

**Comment by matt-seaton** [comment]
Yes it works in blender, but Godot has no such texture coordinates.  And, unfortunately, the shader and mesh skinning pipelines are not amenable to this workflow, so I can't use techniques like triplanar mapping because it works on vertex world position which moves as the model is animated.  I thought I could freeze the model in time for a second, but there's no easy way to get texture maps out of a shader in their material system.

So what I'm being forced to do is implement my own mapping from UV space to object space  in a compute shader, which I have done, and use that to transfer a world space shader using 3d noise into UV space for texture baking, which i have yet to do.

**Comment by joepal1976** [comment]
No more activity for a few months.
