### ISSUE TITLE
Import-Export wavefront obj. file not allowing to upload rig

### ISSUE THREAD

**Issue by DaCreator1** [makehumancommunity/mpfb2#194]
When I press create human it tells me that wavefront obj. file import or export is not enabled in prefrences.

**Comment by joepal1976** [comment]
This sounds as if you are trying to combine an old version of MPFB with blender 4. Try downloading a nightly build rather than, for example, alpha 3.

If you have updated recently and it still does not work, take a look at https://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html

If it still does not work, I'd like to see screenshots of the error message and of the "system and resources" panel.

**Comment by joepal1976** [comment]
No more info for a month, assuming to be resolved.
