### ISSUE TITLE
MakeClothes should be updated to integrate better with the library for body proxies

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#199]
While the integrated MakeClothes is in principle capable of producing body proxies, it requires some manual work. This especially if one wants to add the produced proxy to the library.

MakeClothes should be updated to have a better workflow for body proxies.

**Comment by Vidyut** [comment]
Wishlist:

It could be useful to add a few handy "buttons" like a default cloth modifier and collision on body (Maybe the helpers could be useful to generate basic pin groups), or at least a shapekey for the skirts to not hike up in sitting poses and such - stuff that we end up fixing manually over and over but is really mostly the same thing.

Actually, it might be good to allow a few select vertex group names on clothes/hair/etc. The hair is pretty unusable in spite of such great effort. Even if not curves and cards and such, even a simple lattice modifier might be good enough for many occasions? Surely they can be programmatically ignored? Then we can store stuff using simulation in the library itself. Even better if the clothes file can store the clothes modifier settings, but that may be too much to expect. Also most times we'll end up fiddling with settings anyway, so having to add them isn't a big deal. But newbies can't easily figure out good defaults, and MPFB2 could sort of nudge them right... Right now it becomes a pain to set them up over and over and kind of defeats the purpose of click to add. Simpler to import from a blend file and bypass the library.

This is just a wishlist, not complaints. Since you're already working on it, if any of this can be picked up on the way...

**Comment by joepal1976** [comment]
The fix here is for the makeclothes functionality for proxies. The items from the wish list are interesting too, but I think those items should be a few separate feature request since they don't really have anything to do with the body proxy functionality.

I've thus copied the wish list to #228
