### ISSUE TITLE
MPFB 2 model controls are stopped working...

### ISSUE THREAD

**Issue by MaleficentRick** [makehumancommunity/mpfb2#211]
**Describe the bug**
Whenever I apply a topology, the model controls stop working.  I tried every rig and a few different topologies.

**Checklist**
Blender 4.2.3 LTS.
MPFB 20241017 (But it also had this issue in the "mpfb-2.0-b1.zip" release)

**Screenshots / logs**
[Usage Log.txt](https://github.com/user-attachments/files/17413682/Usage.Log.txt)

**Platform and versions**
 - OS: Windows Windows 10 Home, 22H2, 19045.5011
 - Version of Blender == Blender 4.2.3 LTS.
 - Version of MPFB = MPFB 20241017  (2.0.5 - v2.0-b2)
 - https://files2.makehumancommunity.org/plugins/mpfb2-20241017.zip

**Comment by joepal1976** [comment]
Just checking: Is the "auto refit assets" checkbox in the top of the model panel enabled and/or did you click the "refit assets" button?

I'm guessing what happens here is that the model sliders are actually working in the sense that they change the base mesh, but this is hidden by the topology because auto refit is disabled (which is the default for performance reasons)

**Comment by MaleficentRick** [comment]
"Auto Refit Assets" was unchecked.  That fixed it!  lol
Thank you so much and sorry for the bother!

**Comment by Vidyut** [comment]
That had been puzzling me too - I haven't really figured out the topologies and how to use them - is there a guide somewhere?

**Comment by joepal1976** [comment]
@Vidyut : No, not really. I've started writing guides on assets here: https://static.makehumancommunity.org/mpfb/docs/assets.html

But I haven't gotten as far as to topologies yet. 

I've added #214 for this.

**Comment by joepal1976** [comment]
Assumed to be working as intended.
