### ISSUE TITLE
Finish first version of MakeUp tool

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#212]
Experimental and preliminary code for the MakeUp tool has already been merged to master, but it needs to:

- be cleaned up
- get unit test coverage
- get inline code comments
- fixed with pylint

Also, some testing and user feedback would be nice.

**Comment by Vidyut** [comment]
I did the update just now, and prima facie, stuff seems to work, though the materials have gone wonky and need fixing. 
![ax-makeup-layer](https://github.com/user-attachments/assets/7c0967ae-6b8d-4f6a-be90-b941ee9c37aa)
She isn't supposed to look like she had a shower (and left her hair and clothes dry...)
This is how she looked a few days ago. I've made a few tweaks, but nothing that shiny... This was enhanced +SSS I think.
![ax-close](https://github.com/user-attachments/assets/e95cd45a-ce32-4e38-a8c0-81e6d7e95e4f)
Turned out it had loaded the multilayered shader (though she hadn't been shiny in multilayered either earlier). Loaded enhanced+SSS and now she looks like this:
![ax-enhanced-sss](https://github.com/user-attachments/assets/6162b462-dc7b-45ef-b732-93f3a383234a)
This is with just enhanced
![ax-enhanced](https://github.com/user-attachments/assets/d692906c-034e-4f14-bda3-174ba13fb7af)
![ax-makeskin](https://github.com/user-attachments/assets/9910d971-ddff-45ba-816a-19a5fd7a05e3)
Game looks similar.

So the extra shininess is basically in the enhanced/multilayered stuff. I'm not that great with code, so may not spot issues quickly, but the differences might help cleverer minds see what changed?

Anyway, this is with Makeup. random test, since the character doesn't use makeup, so no need to be too careful. lol.
Not sure what I did wrong, but can't get the test makeup to render. Goes pink. Probably me being a doofus with some image node, but earlier today had an issue with a skin refusing to render as well. Not sure if it is the addon or something I did wrong - but that was the skin. Making a new file and applying the same skin solved it. Gotta go now, but will try to get the makeup to render as well later.
![image](https://github.com/user-attachments/assets/2cb4ebaf-9f25-4017-ba88-27a038c39213)

**Comment by Vidyut** [comment]
All these are just the default skin loaded (other than makeup, of course). Some setting probably changed, and I'll find and dial it down, but the default skin definitely wasn't as shiny - if you compare with the eyes - they are the same in all the renders - the skin is competing with them now. lol.

Unless of course I made some mistake - but there isn't a lot to mistake in loading a basic skin with one diffuse texture - I purposely didn't use many textures so we know what is the shader and what is my images. One day I need to take a solid week and figure stuff out instead of dabbling.

**Comment by Vidyut** [comment]
Lack of confidence in my own settings apart, I think the plugin shouldn't change shaders on existing files - they'd been set up to look how I wanted. I opened two files and it did that glassy skin on both - I don't dare open more. Both shaders had switched to multilayered - I'm very certain that I hadn't set them to multi-layered.

For now, I'm not saving any of the files and hoping that I can figure it out or some future update can restore the shaders or I can disable this upgrade for now and use the previous version.

**Comment by joepal1976** [comment]
MPFB doesn't change already existing materials, if what we are talking about is a blender material existing on an object inside a blend file. What can happen though, is that a material which was created with an earlier blender version looks different when opened in a new version. 

To me, the first image (with the glossy skin) looks as if the character scale is off, but that is just a guess. This has been known to happen because the material needs to know about the scale attribute of the object, and how this is read has changed. 

The pink stuff happend when blender can't find an image texture (for example a skin diffuse texture). 

But if you care to share the blend file where this looks strange, you could upload it here: http://www.makehumancommunity.org/custom.html and I'll have a look at it. All that should probably be a different issue though, as it doesn't really have anything to do with the new makeup functionality.

**Comment by Vidyut** [comment]
Shared. I don't understand a lot of this, but the blender version didn't change. I literally was working on the image and remembered to check here - saw this thread and downloaded the addon version. It took time to download, so I made the other thread and commented about topologies. Download completed. Closed the file I was working on, updated MPFB2, opened the file. Same file. Nothing other than the addon changed. It began with that "wet" look. When I investigated, the shader had been switched - then I made those screenshots, posted them... I must have done something wrong in the update, but I can't figure out what. But blender didn't change. The file was working literally five minutes before... If not the addon, I can't imagine what.

**Comment by Vidyut** [comment]
> MPFB doesn't change already existing materials, if what we are talking about is a blender material existing on an object inside a blend file. What can happen though, is that a material which was created with an earlier blender version looks different when opened in a new version.

Yes, this is what I would expect as well. But I don't use the multilayered material unless I'm making textures - like you'd suggested in another thread here. I'm making different versions for different uses, and they have either MakeSkin texture or Enhanced+SSS. I haven't used Game or plain Enhanced or Multilayered. And I would definitely notice if my model looked like she was dipped in oil. When I checked after seeing the skin, it was definitely multilayered - hard to confuse that wall of a shader with anything else.

**Comment by Vidyut** [comment]
So I played about with the file a bit more, and since it seemed to be an issue with textures, I tried to "pack textures" to see if that helped. It didn't but it gave a clue. It was searching for some textures in scripts/addons - which is where the old plugin was. But now it is in extensions/user_default.

Could it be that it wonkified my materials because it couldn't find what it was looking for?

But I still don't know how to fix this without making those files all over again...

**Comment by joepal1976** [comment]
Did you share a blend file? I don't see it on the custom content section in the asset repo.

Anyway, my best guess here is that something is off with the scale. This is a model where the scale is off by a factor of ten:

![image](https://github.com/user-attachments/assets/f5c369f8-21db-4398-b6ca-9991d3b1db0a)

As you can see in the lower right corner of the image, "MPFB_GEN_scale_factor" is here set to 1.0 while it should be 0.1. I think this looks so-so similar to your images, but I'm not sure it is the same. Still, it doesn't hurt to check if the property is there and has a decent value. If it is there, you could experiment with changing it by a factor of ten downwards or upwards to see if it makes any difference.

**Comment by joepal1976** [comment]
Deleted last message, had errors in it. New attempt follows.

**Comment by joepal1976** [comment]
Did you share a blend file? I don't see it on the web site.

Anyway, my best guess here is that something is off with the scale. This is how a character looks when the scale is off by a factor of ten:

![image](https://github.com/user-attachments/assets/fadd00bc-5241-44c9-b122-801b2ba67e96)

As you can see in the lower right corner, the MPFB_GEN_scale_factor is 1.0 while it should be 0.1. I'm not sure this is the same thing, but it doesn't hurt to see if the value is there. If it is there, you can try to change it by a factor of ten upwards and downwards to see what happens.

**Comment by Vidyut** [comment]
I thought I'd uploaded, but I checked the tab and the file is too big :( 

Will see what I can do to make it smaller.

**Comment by joepal1976** [comment]
The tool is added. Open new issues if further work is needed.
