### ISSUE TITLE
Document the use of proxies/topologies

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#214]
Topologies have a tendency to be confusing, and it's not obvious to user what they are good for. They also cause effects in the UI making users believe something is wrong.

There's a docs hierarchy for assets here: https://static.makehumancommunity.org/mpfb/docs/assets.html

An introduction to topologies should be added there.

**Comment by joepal1976** [comment]
I've added clarifications in the following now, hoping it will make things clearer:

* https://static.makehumancommunity.org/mpfb/docs/assets/concept_proxymeshes.html
* https://static.makehumancommunity.org/mpfb/faq/proxy_no_modeling.html
* https://static.makehumancommunity.org/mpfb/docs/characters/modeling.html

**Comment by joepal1976** [comment]
@Vidyut : maybe you could take a look at these and check whether they makes sens?

**Comment by Vidyut** [comment]
Oh yes. Digging in. 

Quick question, since proxies are clothes, and the sliders aren't seen to work with them because the basemesh is hidden, does this mean that if we refit a proxy, it will take on the characteristics of the basemesh (shape, etc)? I think it might with the clothes logic, but you may want to idiot-proof it for newbies.

Also, is this something one should not do if they have a highly detailed proxy for closeups (the refit might squish more detailed modelling?

**Comment by joepal1976** [comment]
Yes, that's the point of proxies: They take on the shape of the base mesh, but with a different topology of how the vertices are laid out. This is done in the "refitting" loop, same as for clothes.

As you note, there's no technical difference between clothes and proxies. Proxies tend to be matched closely to the body surface of the basemesh, while clothes often are matched against helper geometry. But these are just common practices, not a technical difference. 

So, yes. In theory any mesh can be used as a human body instead of the basemesh. There's a procedure to get it to behave (same as for clothes), but in theory you could have the default cube to act as a human body if you wanted to.

**Comment by joepal1976** [comment]
Assumed to be good enough
