### ISSUE TITLE
Teeth placement

### ISSUE THREAD

**Issue by Vidyut** [makehumancommunity/mpfb2#225]
**Describe the bug**
I'm not sure if this is a me problem or a problem with the model, but the teeth feel like they are set inside and high, so that when the mouth opens, there's an unnaturally excess view of lower teeth and the upper teeth are rarely seen, including in smiles, etc. Nobody else seems to have mentioned it. Is there something I'm supposed to do before adding teeth? Alternatively, if this is expected behaviour, what's a good way to fix this long term for my install if I'd like them to be a bit lower and slightly more forward by default?

I just move them. I'm not a mega animator and I've got by doing this, but I don't know if that will fail at some point because the weights are nor right or bones are elsewhere, etc.

It has always been like this, so I don't think it is about versions.

**Comment by joepal1976** [comment]
I think this is a problem with the asset rather than a bug per se. One solution might be to produce a new asset by taking an existing one, moving it to a better position and then refitting it via makeclothes.

The same problem has been reported with MakeHuman: http://www.makehumancommunity.org/forum/viewtopic.php?f=18&t=20928&p=62412#p62410

**Comment by Vidyut** [comment]
This is so obvious when you say it, I'm wondering why I didn't think of refitting the same asset how I want it. Facepalm. Thanks. This is resolved. I will do this. I can make clothes and such. I assume it is the same for teeth.
