### ISSUE TITLE
Addon not listed as installed in blender 2.92

### ISSUE THREAD

**Issue by migvel** [makehumancommunity/mpfb2#25]
Hello, in Windows 10, Blender 2.92.

After I install the addon using the zip release, I see the message:

`Modules Installed () from 'zip path' into 'addons path'`

But i cannot see the addon installed in the addon's list. Installing it by unzipping it in the addons directory also seems 
that is not working.

Thanks.

**Comment by joepal1976** [comment]
The official minimum requirement for blender is 3.0.0, although the technical hard limitation is 2.93. My guess is that blender filters the addon from the list since your blender version is lower than what the addon lists as minimum.

If you want to attempt to use it with 2.92 anyway, you can try the unzip method and change line 8 in https://github.com/makehumancommunity/mpfb2/blob/master/src/mpfb/__init__.py so that it instead lists (2, 92, 0).

But I'm no longer testing with blender 2.9x and will not maintain backwards compatibility when adding new features.

**Comment by joepal1976** [comment]
I'll see if I can make the minimum requirement more easy to see when downloading, so marking this issue for documentation.

**Comment by migvel** [comment]
Hello, thanks.

I tried with 3.1 but i have the same issue, I installed by unzipping the directory containing the addon.

But still the same situation, should it have the same name as in the folder in the installed addon list?

Any way to debug here? I might give some more info.

Regards.

**Comment by migvel** [comment]
I copied the directory inside the realease, mpfb2-2.0.0-a1\src\mpfb in the main addon folder and now appears as an installed 
addon, and I can activate it.
