### ISSUE TITLE
Incorrect refitting for toes...

### ISSUE THREAD

**Issue by hwy1992129** [makehumancommunity/mpfb2#34]
As shown in the image below, parameters of feet are modified. Click refit doesn't work with toes joints.... Is it bug?
![QQ图片20220531105355](https://user-images.githubusercontent.com/70329303/171205849-46b28c88-b8e9-4ab7-b7bf-39265e2afb89.png)

**Comment by joepal1976** [comment]
Thank you for the bug report. I have been able to replicate it locally, so can confirm the issue.

**Comment by joepal1976** [comment]
It was a bug where the refitting algorithm erroneously assumed that the rig was "default no toes", so it didn't try to refit the toe joints. This should have been fixed in https://github.com/makehumancommunity/mpfb2/commit/8d72a0f8736c1b80909084415b723574eba70286

Can you check if this solves your problem?

**Comment by joepal1976** [comment]
Closing handled issues with no additional info for a month

**Comment by hwy1992129** [comment]
Sorry for the late response... It was fixed. Thanks for your work.
