### ISSUE TITLE
4 Problems I found when adding Rigify Rig

### ISSUE THREAD

**Issue by TACarp** [makehumancommunity/mpfb2#6]
The "add rigify rig" button under "rigging" then under "add rig" works well. I have notice four what I believe are errors.

- The eyebrow weight painting distorts the forehead and shape of forward scalp too much when the eyebrow bones are moved.
- The "master_eye.l" and "master_eye.r" bones, with custom square bone shapes, are rotated about 45 degrees on the Y-axis than they should be. The idea is, you should be able to scale these bones on the Z-axis and make the eyes squint. Right now it does that in a distorted way.
- The breast bones are on the back of the character instead of the front and, when moved, they move both the back and front of the character on the upper torso.
- Right now the custom bone shapes for the ears are different for left and right. I think this is just cosmetic and doesn't affect rig usability.

**Comment by joepal1976** [comment]
Thanks. Yes, the weight painting in the face is very, very crude. This especially in the face area. Right now it's based on an automatic weight assignment, and it needs to be gone through manually to fix. This is a bit down on the todo list, so if you want to take a swipe at it, the general procedure would be this:

- Create a new character
- Add a rigify rig to it (without generating the final rig)
- Do weight painting as you'd usually do
- When satisfied, go to object mode and select the rig. Then go to developer -> save weights and attach the json file here or make a pull request. 

Otherwise I'll get around to it once I'm done with the clothes and library stuff.

The eye bones I hadn't noticed. I'll look into it, and the breast and ear bones shouldn't be too hard to fix.

**Comment by joepal1976** [comment]
I'll deal with weight painting in #9

**Comment by TACarp** [comment]
It seems in some recent updates to this addon the ability to name the rigify the rig before generating was removed. This is important if you append/link multiple rigify rigged characters to the same blender document so they each get their own specifically named rig_ui.py blender text data-block to execute upon append/link so they can each have the own user interface. The default named "rig_ui.py" can only be executed for the first character, while "<CharacterName>_ui.py" can be executed along with other uniquely made/ named UI generation scripts.. Was this a mistake that this name function was removed, or am I not understanding something?

**Comment by joepal1976** [comment]
It might very well be a mistake, as I'm not really all that used to rigify pipelines. It was my understanding that setting this name can be done with the standard blender ui:

![rigify_name](https://user-images.githubusercontent.com/10105480/125802030-ad010e6a-4aff-49ca-86f8-9561080896f0.png)

Having entered a name here, it will use it when generating:

![rigify_name_2](https://user-images.githubusercontent.com/10105480/125802131-9ebc3b4c-9208-414c-94bb-3a9dc99351c3.png)

If this is experienced as cumbersome, I don't have any problems with modifying the UI to make the process smoother. 

What is the desired behavior?

**Comment by TACarp** [comment]
Joe, you can do this with the standard RIgify Blender UI, but it does not parent the generated rig to the MH meshes like the MH UI buttons do.

**Comment by joepal1976** [comment]
I think all relevant issues in this thread has been fixed in PR https://github.com/makehumancommunity/mpfb2/pull/41

Open a new specific issue if something is still wrong.
