### ISSUE TITLE
Porting MPFB2's walk cycle system to UPBGE

### ISSUE THREAD

**Issue by 12D687** [makehumancommunity/mpfb2#61]
I know this is out of your scope. But I'm wondering if you can attach your walk cycle/animation in UPBGE's (Uchronia Project Blender Game Engine) Python Component (see https://upbge.org/docs/latest/manual/manual/python_components/introduction.html   https://upbge.org/docs/latest/manual/manual/python_components/getting_started/character_controller_templates.html#character-controller-component
https://github.com/UnidayStudio/UPBGE-CharacterController/blob/master/Source/CharacterController.py for details). Because it comes really handy if you make game and you want animate walk cycle. Btw the mpfb2 will work in UPBGE despite it uses Blender version 3.0

**Comment by joepal1976** [comment]
This is the first I even hear of UPBGE. It sounds like a nice and interesting project, and I'm all for getting better MPFB2 support in it. However, two points: 

First, the walk cycle system in MPFB2 is highly experimental and not really fit for general use. I'd really recommend against basing anything serious on it, as everything points towards having to redo much of it from scratch in order to finalize it. 

Second, as I'm not familiar with UPBGE it'd be a bit of an uphill for me to port stuff to it. This would have to compete with everything else that is needed in order to take MPFB2 to a first stable release. Thus it'd have to come pretty far down on the todo list. 

This said, if you or someone else wants to take a swipe at taking stuff from MPFB2 and provide better support for it in UPBGE, and I'm all for it. I will then provide what support and know-how I can in order the help you along.

**Comment by joepal1976** [comment]
No more activity for quite some time, closing.
