### ISSUE TITLE
Having Problems with weight Paint

### ISSUE THREAD

**Issue by Atta333** [makehumancommunity/mpfb2#71]
Hi I just using this amazing add on in Blender but i am having problem with adding new geometry how do i weight paint the new geometry

**Comment by joepal1976** [comment]
Generally, you would not add geometry to an _active_ human mesh, since there's a lot that will get in the way. Rather, once you've finished the macro detail modeling using sliders, you would bake shape keys and remove helpers in order to continue modeling. Doing so will turn the human mesh inactive, in the sense that you no longer be able to use modeling sliders, and equipping clothes might produce random results. But operations such as weight painting will work a lot more smooth.

Basically there are a few different ways of going here. It is hard to say which one is the most appropriate without knowing what it is you want to achieve. 

1. Bake shape keys and remove helpers. This will make the human mesh start acting like any other blender mesh. To do this, go to the "operations" -> "basemesh" panel and use the appropriate buttons. 
2. Add geometry by creating clothes rather than by modifying the human. This might be appropriate for, say, adding horns or a tail. To do this, download and install the MakeClothes tool from the same location you found MPFB
3. Create a body proxy with the added geometry. The process of making a body proxy is largely the same as for creating clothes, but you change the extension to .proxy in the end, and put it in the data/proxymeshes directory instead of data/clothes
4. Do not add geometry at all. Instead, create a normal map simulating the geometry. See https://www.youtube.com/watch?v=F5n8gJdDmQ8
