### ISSUE TITLE
Male targets does not seem to work, there is no visible effect on the male proxy

### ISSUE THREAD

**Issue by 12D687** [makehumancommunity/mpfb2#76]
In the modelling section there is a three "widgets" (Penis-length-decr-incr, Penis-testicles-decr-incr and Penis-circ-decr-incr) which won't work despite that I had correctly loaded simple penis topology and had enable it. Also there is no error messages.

**Comment by joepal1976** [comment]
Thanks. This sounds like a bug rather than something you missed. I'll look into it.

**Comment by joepal1976** [comment]
The targets work for me using wolgade's male proxy. 

Just to check: Did you click the "refit assets to base mesh" button after changing the target values? 

![image](https://user-images.githubusercontent.com/10105480/212012597-b140fa14-be44-43bc-8d35-23bff662d1fa.png)

The modeling panel only changes the base mesh, whereas the proxy is a secondary mesh attached to the base mesh. It will not be updated live for performance reasons. Thus, if you change a target value, you will have to click the refit button in order to see what effects the change have on the proxy.

If you want to do live modling and see what happens, you could instead temporarily hide the proxy, and temporarily change the mask modifier on the base mesh:

![image](https://user-images.githubusercontent.com/10105480/212013257-b54bd73f-f71a-4355-9c0c-562114015083.png)

This way you will see live what happens to the relevant parts. Once you're finished modeling, you can set the mask back to "body", show the proxy again and click the "refit assets" button to get the change visible on the proxy.

If none of the above helps: Exactly which proxy are you using?

**Comment by ashledombos** [comment]
Not sure if it helped the OP, but it helped me, I had difficult to understand how to apply targets to proxy741 after this one is loaded.

I did not understand that I have to select the .body mesh in collections (the original one), then model menu appears again, then you can play with sliders, then you need to refit asset to basemesh to see what happens to proxy mesh.

Thanks

**Comment by joepal1976** [comment]
Well, if many users run into the same confusion, then that's a good indication that the user interface is unclear and that some UX work is needed.

**Comment by 12D687** [comment]
Hi thanks now it works for me. Btw I use porky11 simple penis asset.
