### ISSUE TITLE
The behaviour of the model panel is confusing, especially if a proxy is used

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#78]
Several people have run into confusion regarding how modeling sliders work. For example, they do not easily find the modeling panel once having added other mesh assets than the base mesh. Also, if a proxy is added, the modeling sliders seem to do nothing as it is not immediately apparent that the "refit assets" button has to be clicked to update proxies (see for example #76).

Some UX work is needed here, so that new users do not run into the same confusion.

**Comment by joepal1976** [comment]
With c602d14 the model panel will appear as long as a related object with a parent/child/sibling relation to a basemesh is selected. Further, there is now a checkbox for whether related objects should be automatically refitted when a modeling slider is changed. This should make modeling with an enabled proxymesh much more intuitive. 

![image](https://user-images.githubusercontent.com/10105480/213366253-7b3c4e78-5fa6-4d9c-84e7-151571695c3a.png)

**Comment by ashledombos** [comment]
This is a quite big improvement, IMHO worth an announcement for wider testing. Why not in MakeHuman news?

**Comment by ashledombos** [comment]
I’m trying with «male muscle 13290»: for me, it works perfectly, bravo, good job.

Indeed, there is a slight lag, I suppose that for slow machines, it is more interesting to modify directly the base mesh rather than the proxy, by switching their visibility. However, for custom targets or for genitals, it is clear that it remains more interesting to see the changes in almost real time rather than spending time scrolling up and down for applying targets.

I was wondering, certainly a stupid idea, but for slow computers, maybe it would be less heavy if we could toggle an option to increase time between two automatic refits (for instance 1 second instead of real time) ?

**Comment by joepal1976** [comment]
@ashledombos In most other contexts, I'd say your suggestion about delayed updates would be a good idea. Unfortunately, blender does not play well with asynchronous tasks. While it might be theoretically possible to add a timer to periodically update the viewport during modeling, this is something that would be a very complex thing to add. 

So I'm going to close this issue as completed for now, and then maybe revisit the delayed updates track at some point in the future.
