### ISSUE TITLE
How to use custom Makehuman targets in MPFB2

### ISSUE THREAD

**Issue by aheger76** [makehumancommunity/mpfb2#95]
Hi! 
Is it possible - if yes, how  (e.g link to the relevant documentation of this topic )- to use custom targets created by  Makehuman / Maketraget2 with MPFB2?
Thanks in advance.

**Comment by joepal1976** [comment]
Making this more intuitive for users has been on my todo list for a while. I've created a separate issue for tracking that: #96 

To answer the question though... In order to install a new custom target, it needs to be copied into the "custom" directory under user data. To figure out where the custom dir is, go to "system and resources" -> "directories" and click "user files". Then navigate into "data". Here you should find a directory "custom". If it doesn't exist, create it manually. 

After having copied the target into the custom directory and restarted blender, the target should be listed under custom targets on the modeling tab.

**Comment by joepal1976** [comment]
In tomorrow's nightly build there will be a button "install custom target" under "apply assets" -> "library settings" -> "install assets". If you're comfortable with running from source, it's pushed to master now.
